services:
  frontend:
    build: ./front
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: ./api
    ports:
      - "5000:5000"
    volumes:
      - ./api:/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge